name: Generate Datas
on:
  schedule: # execute every 12 hours
    - cron: "* */24 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SNAKE_TOKEN }}
    
      # Snake Animation
      - uses: Platane/snk@v3
        with:
          # github user name to read the contribution graph from (**required**)
          # using action context var `github.repository_owner` or specified user
          github_user_name: ${{ github.repository_owner }}
      
          # list of files to generate.
          # one file per line. Each output can be customized with options as query string.
          #
          # supported options:
          #  - palette:     A preset of color, one of [github, github-dark, github-light]
          #  - color_snake: blue
          #  - color_dots:  Coma separated list of dots color.
          #                 The first one is 0 contribution, then it goes from the low contribution to the highest.
          #                 Exactly 5 colors are expected.
          outputs: |
            dist/github-snake.svg?color_snake=#0a66c2
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#0a66c2
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Commit and Push to the `main` branch under `output` folder
      - name: Commit and Push Generated Files
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          mkdir -p output
          mv dist/* output/ || true
          git add output/
          git commit -m "Update snake animation files [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.SNAKE_TOKEN }}
